git_source(:github) { |name| "https://github.com/#{name}.git" }

source 'https://rubygems.org'

gem 'rdiscount', :github => 'davidfstr/rdiscount'
gem 'jsduck', :github => 'appcelerator/jsduck', :branch => 'sgtcoolguy-es6'
gem 'compass'